### ISSUE TITLE
Issue Encountered while Running PoPS

### ISSUE THREAD

**Issue by 12zkchen** [Marijn-Schipper/FLAMES#1]
First and foremost, I would like to express my gratitude for developing FLAMES for GWAS gene prioritization. As I attempted to execute FLAMES with my dataset, I encountered a hurdle during the analysis step "3. Run PoPS on the generated MAGMA z-scores." Specifically, I faced the following error message: "raise KeyError(f"{not_found} not in index") KeyError: "['ENSG00000269831', 'ENSG00000269308', 'ENSG00000268179', ..., 'ENSG00000185973'] not in index".
Upon investigation, I realized that while my magma.genes.out file contains 19858 rows, the accompanying gene_annot.txt file only encompasses 18383 rows. Consequently, over a thousand ‘ENSGxxx’ entries cannot find a match, impeding the analysis process.
Given this discrepancy, I am reaching out to seek your guidance on resolving this issue. Do you have any recommendations or solutions to enable the successful execution of the analysis?
Your assistance in this matter would be greatly appreciated.

**Comment by Marijn-Schipper** [comment]
Hi there,
Thanks for your interest in FLAMES. You have highlighted something that I indeed need to change in the documentation. The magma .genes.out file is indeed different from what is compatible with the munged PoPS features I have shared. The munged features that I have shared correspond to the PoPS gene_annot file from the original publication. You therefore have two options. You can do that by either doing: 

1: You can run PoPS with your 19858 genes of interest. You can do that by either doing: 
Downloading the raw PoPS features from [this](https://www.dropbox.com/sh/o6t5jprvxb8b500/AADZ8qD6Rpz4uvCk0b5nUnPaa/data?dl=0&subfolder_nav_tracking=1) link. Follow the tutorial on munging your features from the [PoPS GitHub](https://github.com/FinucaneLab/pops). Make sure that you specify a gene annotion file that matches your 19858 MAGMA genes. 

or

2: Run [MAGMA](https://cncr.nl/research/magma/) by annotating the SNPs to this [this](https://github.com/Marijn-Schipper/FLAMES/files/14935368/gene_annot_jun10.txt) file, which matches the gene annotation from the original PoPS publication. From the annotation file you can run  MAGMA for your summary statistics. You can then proceed with the analysis as usual.

How did you generate the MAGMA Z scores you are currently using if I may ask? I would like to ensure that this transition is as smooth as possible. 

Let me know if you encounter any other problems.
Best,
Marijn

**Comment by 12zkchen** [comment]
Hi Marijn,

Thank you for your swift response! It's clear now why my analysis was hitting roadblocks. I followed your suggestions today, but I had another questions.

Regarding the first option, how can I obtain a gene annotation file that matches my 19858 MAGMA genes?

As for the second option, I'm a bit unclear on how to proceed with running MAGMA by annotating the SNPs to the file (gene_annot_jun10.txt). Even after removing over 1000+ genes that couldn't be matched in the gene_annot.txt file, leaving me with 18k genes for analysis, the process still couldn't proceed.

Step 1 and 2 were performed by uploading my summary statistics to FUMA and running MAGMA there, and downloading the final results (i.e.,the MAGMA Z scores).

Your insight and help are truly appreciated! 

Best regards,
Zekai

**Comment by Marijn-Schipper** [comment]
Hi Zekai,

Option 1:
The PoPS github specifies that for munging the features you need a gene annot file with the following requirements "Path to gene annotation table. For the purposes of this script, only require that there is an ENSGID column". I guess you can use the MAGMA.genes.out file for this. 

Option 2: 
I have looked into removing output from a MAGMA genes.out as well , but PoPS also parses the genes.out.raw, which is a corresponding table and will throw errors saying that the two tables do not match. If you want to use my munged features then you would have to run MAGMA manually. Step1 when running MAGMA from scratch on your summary statistics is create a snp annotation file. For this you need your GWAS file and a gene location file. If you use the gene_annot_jun10.txt as the gene location file your MAGMA-Z scores will be compatible with the munged features I have provided.

Let me know if you get stuck on the execution of either of the two options. 
Best,
Marijn

**Comment by 12zkchen** [comment]
Hi Marijn,

Thank you for your further clarification. I tried Option 1 by downloading the raw PoPS features (i.e., PoPS.features.txt.gz) from the provided link and using the MAGMA.genes.out file for munging the features. However, I only obtained the results in pops_features.rows.txt format, which is insufficient to support subsequent analyses.

Regarding Option 2, I haven't attempted it yet. Using gene_annot_jun10.txt as the gene location file might result in the loss of information for over 1000 genes, potentially impacting the results.

As neither of the options seems to resolve the issue, I'm still unable to run FLAMES successfully. If you make any optimizations or adjustments to the documentation in the future to streamline the analysis process, it would be greatly appreciated.

Best regards,
Zekai

**Comment by Marijn-Schipper** [comment]
Dear Zekai,

Doing option two will indeed potentially impact the result as the likelihood of the missing genes being predicted will be lower. For option 1 I would refer you to the PoPS Github, where they document running PoPS for your own MAGMA output. You should be able to process the features using step 0, munging the features for downstream use.

**Comment by Marijn-Schipper** [comment]
Dear Zekai,

I have now uploaded a new version of PoPS features that is compatible with FUMA MAGMA Z-scores, and protein coding ENSEMBL genes v102/v110. 
This should resolve the problem.
Please reopen a ticket if you encounter new errors. 
Best,
Marijn
